#!/bin/bash
time gcc backend_x86.c lexer.c parser.c my_string.c main.c types.c analyzer.c tac.c registers.c \
    -DDEBUG_RUNTIME_CHECKS \
    -static \
    -Wunused-but-set-variable \
    -Wreturn-type \
    -Wno-discarded-qualifiers \
    -g  \
    -o compiler \
    && ./compiler
